-
  conditions:
    zone_provenance_produit: "EU"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    zone_provenance_produit: "Andorra"
    age: "< 17"
    categorie_produit: "'parfum' or 'eau-de-toilette'"
  results:
    importation_interdite: true
-
  conditions:
    zone_provenance_produit: "Andorra"
    quantite_produit: "<= 75"
    age: ">= 17"
    categorie_produit: "parfum"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    zone_provenance_produit: "Andorra"
    quantite_produit: "> 75"
    age: ">= 17"
    categorie_produit: "parfum"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    zone_provenance_produit: "Andorra"
    quantite_produit: "<= 375"
    age: ">= 17"
    categorie_produit: "eau-de-toilette"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    zone_provenance_produit: "Andorra"
    quantite_produit: "> 375"
    age: ">= 17"
    categorie_produit: "eau-de-toilette"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    zone_provenance_produit: "Andorra"
    valeur_produit: "<= 450"
    age: "< 15"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    zone_provenance_produit: "Andorra"
    valeur_produit: "> 450"
    age: "< 15"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    zone_provenance_produit: "Andorra"
    valeur_produit: "<= 900"
    age: ">= 15"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    zone_provenance_produit: "Andorra"
    valeur_produit: "> 900"
    age: ">= 15"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    age: "< 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'avion' or 'bateau'"
    valeur_produit: "<= 150"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    age: "< 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'avion' or 'bateau'"
    valeur_produit: "value > 150 or value <= 700"
  results:
    taux_droits_douane_max: 0.025
    tva: 0.20
-
  conditions:
    age: "< 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'avion' or 'bateau'"
    valeur_produit: "> 700"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    age: ">= 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'avion' or 'bateau'"
    valeur_produit: "<= 430"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    age: ">= 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'avion' or 'bateau'"
    valeur_produit: "value > 430 or value <= 700"
  results:
    taux_droits_douane_max: 0.025
    tva: 0.20
-
  conditions:
    age: ">= 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'avion' or 'bateau'"
    valeur_produit: "> 700"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    age: "< 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'train' or 'route'"
    valeur_produit: "<= 150"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    age: "< 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'train' or 'route'"
    valeur_produit: "value > 150 or value <= 700"
  results:
    taux_droits_douane_max: 0.025
    tva: 0.20
-
  conditions:
    age: "< 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'train' or 'route'"
    valeur_produit: "> 700"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    age: ">= 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'train' or 'route'"
    valeur_produit: "<= 300"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    age: ">= 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'train' or 'route'"
    valeur_produit: "value > 300 or value <= 700"
  results:
    taux_droits_douane_max: 0.025
    tva: 0.20
-
  conditions:
    age: ">= 15"
    zone_provenance_produit: "non_EU"
    moyen_transport: "'train' or 'route'"
    valeur_produit: "> 700"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
