-
  conditions:
    douanes_zone_provenance_produit: "EU"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    age: "< 17"
    categories_produit: ["parfum", "eau-de-toilette"]
  results:
    importation_interdite: true
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    douanes_quantite_produit: "<= 75"
    age: ">= 17"
    categories_produit: ["parfum"]
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    douanes_quantite_produit: "> 75"
    age: ">= 17"
    categories_produit: ["parfum"]
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    douanes_quantite_produit: "<= 375"
    age: ">= 17"
    categories_produit: ["eau-de-toilette"]
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    douanes_quantite_produit: "> 375"
    age: ">= 17"
    categories_produit: ["eau-de-toilette"]
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    valeur_produit_importe: "<= 450"
    age: "< 15"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    valeur_produit_importe: "> 450"
    age: "< 15"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    valeur_produit_importe: "<= 900"
    age: ">= 15"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    douanes_zone_provenance_produit: "Andorra"
    valeur_produit_importe: "> 900"
    age: ">= 15"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    age: "< 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["avion", "bateau"]
    valeur_produit_importe: "<= 150"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    age: "< 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["avion", "bateau"]
    valeur_produit_importe: "> 150 <= 700"
  results:
    taux_droits_douane_max: 0.025
    tva: 0.20
-
  conditions:
    age: "< 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["avion", "bateau"]
    valeur_produit_importe: "> 700"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    age: ">= 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["avion", "bateau"]
    valeur_produit_importe: "<= 430"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    age: ">= 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["avion", "bateau"]
    valeur_produit_importe: "> 430 <= 700"
  results:
    taux_droits_douane_max: 0.025
    tva: 0.20
-
  conditions:
    age: ">= 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["avion", "bateau"]
    valeur_produit_importe: "> 700"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    age: "< 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["train", "route"]
    valeur_produit_importe: "<= 150"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    age: "< 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["train", "route"]
    valeur_produit_importe: "> 150 <= 700"
  results:
    taux_droits_douane_max: 0.025
    tva: 0.20
-
  conditions:
    age: "< 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["train", "route"]
    valeur_produit_importe: "> 700"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
-
  conditions:
    age: ">= 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["train", "route"]
    valeur_produit_importe: "<= 300"
  results:
    taux_droits_douane_max: 0
    tva: 0
-
  conditions:
    age: ">= 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["train", "route"]
    valeur_produit_importe: "> 300 <= 700"
  results:
    taux_droits_douane_max: 0.025
    tva: 0.20
-
  conditions:
    age: ">= 15"
    douanes_zone_provenance_produit: "non_EU"
    moyens_transport: ["train", "route"]
    valeur_produit_importe: "> 700"
  results:
    taux_droits_douane_max: 0.17
    tva: 0.20
