graph TD
  subgraph Server
    douanesWebApi(API web douanes)
    nomenclatureXml>Nomenclature XML]
    ofExtDouanes(OpenFisca extension douanes)
    ofFrance(OpenFisca-France)
    ofWebApi(API web OpenFisca)
  end
  subgraph Clients
    www((Site web))
    mobileApp((Application<br>mobile))
  end
  ofExtDouanes -.-> nomenclatureXml
  ofExtDouanes --> ofFrance
  douanesWebApi -- WSGI --> ofWebApi
  ofWebApi --> ofExtDouanes
  www -. HTTP request .-> douanesWebApi
  mobileApp -. HTTP request .-> douanesWebApi
